name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 檢出代碼
      - uses: actions/checkout@v3

      # 設置 Flutter 環境
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4' # 更新為你使用的 Flutter 版本

      # 安裝依賴
      - name: Install dependencies
        run: flutter pub get

      # 構建 Flutter Web 應用
      - name: Build Flutter Web
        run: flutter build web

      # 創建 .nojekyll 文件以禁用 Jekyll
      - name: Create .nojekyll file
        run: echo > build/web/.nojekyll

      # 部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
